# Generated by Django 5.1.1 on 2024-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivage_Chaussure',
            fields=[
                ('id_arrivage', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_arrivage', models.DateField()),
                ('description_ch_arrivage', models.TextField()),
                ('pointure_min_arrivage', models.IntegerField()),
                ('pointure_max_arrivage', models.IntegerField()),
                ('quantite_arrivage', models.IntegerField()),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_arrivage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_passage_client', models.DateField(blank=True, null=True)),
                ('nom_client', models.CharField(max_length=10)),
                ('prenom_client', models.CharField(max_length=10)),
                ('numero_client', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('adresse_client', models.CharField(max_length=10)),
                ('remarque_achat', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
