# Generated by Django 5.1.1 on 2024-10-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_vente', models.DateField()),
                ('description_chaussure', models.CharField(max_length=30)),
                ('pointure_chaussure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_boutique.client')),
            ],
        ),
    ]
